# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov(token = "a1c61c8e-9b86-4efc-b08b-ccb3dd260243")'

